name: Python CI

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2 

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Ejecutar la aplicación y simular entradas
      run: |
        # Ejecutar el script de la aplicación y simular entradas usando 'echo' y 'pipe' para enviar datos a la app.
        echo -e "Andree\nandre@gmail.com\ns\nJulio\njulio@gmail.com\nn" | python app.py  

    - name: Verificar la salida de la aplicación
      run: |
        # Verifica que los usuarios se hayan agregado correctamente y que la salida contenga los datos esperados.
        output=$(echo -e "Andree\nandre@gmail.com\ns\nJulio\njulio@gmail.com\nn" | python app.py)
        echo "$output"
        if [[ "$output" != *"Usuario Andree agregado correctamente con ID 1."* ]]; then
          echo "Error: Andree no agregado correctamente"
          exit 1
        fi
        if [[ "$output" != *"Usuario Julio agregado correctamente con ID 2."* ]]; then
          echo "Error: Julio no agregado correctamente"
          exit 1
        fi
        if [[ "$output" != *"Usuarios almacenados:"* ]]; then
          echo "Error: No se muestra la lista de usuarios almacenados"
          exit 1
        fi

    - name: Ejecutar pruebas
      run: |
        python -m unittest discover tests  # Ejecuta las pruebas unitarias ubicadas en el directorio 'tests'
